#!/usr/bin/env python3

import json
from pathlib import Path

from tag_sensor.config import Config

file = Path( __file__ ).parent.parent / 'tag-sensor.schema.json'
schema = json.dumps( Config.model_json_schema(), indent = 2 )
file.write_text( schema )
